type DocumentCopy = {
  title: string;
  intro: string;
  sections: Array<{ heading: string; body: string }>;
  sourceNote: string;
};

const documents: Record<string, DocumentCopy> = {
  tr: {
    title: 'Kaynak dokümanların Türkçe teknik özeti',
    intro: 'Bu bölüm, ambalaj geri dönüştürülebilirliği rehberi ile etiket malzemelerine ilişkin güvenlik ve uyumluluk beyanlarının içeriklerinin Rotabil web sitesi için Türkçeye uyarlanmış özetidir. Kaynak belgeler ayrı bir PDF olarak yayınlanmamaktadır.',
    sections: [
      { heading: 'Geri dönüştürülebilirlik bir sistem özelliğidir', body: 'Bir ambalajın geri dönüştürülebilirliği yalnızca malzemenin adına bağlı değildir. Geri dönüşüm için tasarım, ayrı toplama, ayırma, yeniden işleme ve ortaya çıkan ikincil hammaddenin yeni ürünlerde kullanılabilmesi birlikte değerlendirilir. Yerel toplama ve geri dönüşüm altyapısı ile gerçek kullanım koşulları nihai sonucu etkiler.' },
      { heading: 'EPR ve PPWR bağlantısı', body: 'Genişletilmiş Üretici Sorumluluğu (EPR) sistemlerinde üretici ve ithalatçılar ambalajın kullanım ömrü sonundaki yönetiminde sorumluluk üstlenir. Ambalajın geri dönüştürülebilirlik performansı, bazı pazarlarda EPR ücretlerini etkileyebilir. Bu nedenle ambalaj türü, ağırlığı ve ülkeye özgü bildirim kuralları ayrı ayrı değerlendirilmelidir.' },
      { heading: 'Karton ve etiket seçimi', body: 'Karton kutular üzerindeki standart kâğıt etiketler, mevcut kâğıt geri dönüşüm yöntemleriyle genel olarak yönetilebilir. Elyaf bazlı etiketler geri kazanılan elyaf verimini destekleyebilir. Elyafın ayrılmasını kolaylaştıran yapıştırıcılar tercih edilebilir; plastik etiketler, ıslak mukavemetli kâğıtlar ve özel yapıştırıcılar ise miktar, tasarım ve yerel tesis kurallarına göre ayrıca incelenmelidir.' },
      { heading: 'Daha sürdürülebilir ambalaj için kontrol listesi', body: 'Malzeme sayısını ve gereksiz bileşenleri azaltmak, geri dönüşüm akışına uygun tasarım yapmak, etiket-yapıştırıcı kombinasyonunu gerçek kullanım ve geri dönüşüm koşullarında değerlendirmek, tedarikçi beyanlarını güncel tutmak ve ambalajın türü ile ağırlığını izlemek temel kontrol noktalarıdır.' },
      { heading: 'Tedarikçi güvenlik ve uyumluluk beyanlarının kapsamı', body: 'Tedarikçi beyanları; ham maddeler, yarı mamuller, üretim süreçleri ve ürün güvenliği hakkındaki mevcut bilgi, güvenlik bilgi formları ve sınırlı tedarikçi/üçüncü taraf değerlendirmelerine dayanabilir. Bu tür beyanlar genel rehberlik sağlar; müşteri kullanımına özgü yeterlilik değerlendirmesinin veya mevzuat incelemesinin yerine geçmez.' },
      { heading: 'Madde 5: ağır metaller ve PFAS', body: 'AB 2025/40 Madde 5 kapsamında kurşun, kadmiyum, cıva ve hekzavalent kromun ambalaj bileşeni başına toplamı 100 mg/kg sınırıyla değerlendirilir. Tedarikçi beyanında bu maddelerin bilerek eklenmediği ve temsili malzemelerde sınırın altında sonuçlar bulunduğu belirtilmektedir; bu ifade her ürün veya kullanım için otomatik garanti değildir. Gıda ile temas eden ambalajlarda PFAS limitleri, amaçlanan kullanım ve güncel mevzuata göre ayrıca doğrulanmalıdır.' },
      { heading: 'Diğer madde başlıkları', body: 'Beyanlarda formaldehit, dimetil fumarat, okso-bozunur katkılar, ozon tabakasını incelten maddeler, bazı ağır metaller, nanomalzemeler ve belirli PFAS türlerinin bilerek kullanılmadığına ilişkin tedarikçi bilgileri yer alır. PVC, PVdC, özel film yapıları, SVHC ve benzeri istisnalar ürün bazında değişebilir; bu nedenle teknik bilgi föyü ve ürün kodu üzerinden doğrulama gerekir.' },
      { heading: 'Rotabil uygulaması ve sınırlar', body: 'Rotabil’in karton ambalaj yaklaşımı; güncel tedarikçi belgeleri, teknik föyler, gerektiğinde test raporları, tedarikçi/ürün/lot bağlantısı ve yıllık belge gözden geçirmesiyle yürütülür. Bu sayfa hukuki danışmanlık, gıda ile temas uygunluk sertifikası veya tüm ürünler için koşulsuz uygunluk beyanı değildir. Son değerlendirme ürün bileşimi, kullanım koşulları, yerel altyapı ve yürürlükteki mevzuata göre yapılmalıdır.' },
    ],
    sourceNote: 'Kaynak içerikler: Eylül 2024 tarihli ambalaj geri dönüştürülebilirliği rehberi ve 25 Haziran 2026 tarihli etiket malzemeleri güvenlik/uyumluluk beyanı. Kaynak belgelerin kendi uyarıları gereği bilgiler genel niteliktedir ve mevzuat değişikliklerini her zaman yansıtmayabilir.',
  },
  en: {
    title: 'English technical summary of the source documents',
    intro: 'This section is an English adaptation for the Rotabil website of the packaging recyclability guide and the safety and compliance statements for label materials. The source documents are not published as separate PDFs.',
    sections: [
      { heading: 'Recyclability is a system property', body: 'Recyclability is not determined by the name of a material alone. Design for recycling, separate collection, sorting, reprocessing and the use of the resulting secondary raw material must be considered together. Local collection and recycling infrastructure and actual conditions of use affect the final outcome.' },
      { heading: 'EPR and the PPWR connection', body: 'Under Extended Producer Responsibility (EPR) schemes, producers and importers take responsibility for managing packaging at end of life. Recyclability performance may affect EPR fees in some markets. Packaging type, weight and country-specific reporting rules therefore need to be assessed separately.' },
      { heading: 'Carton and label choices', body: 'Standard paper labels on cardboard boxes can generally be managed through existing paper recycling methods. Fibre-based labels may support recovered-fibre yield. Adhesives that facilitate fibre separation can be preferred; plastic labels, wet-strength papers and specialist adhesives require separate review based on quantity, design and local facility rules.' },
      { heading: 'Checklist for more sustainable packaging', body: 'Key checks include reducing unnecessary materials and components, designing for the relevant recycling stream, assessing the label and adhesive combination under real use and recycling conditions, keeping supplier statements current, and recording packaging type and weight.' },
      { heading: 'Scope of supplier safety and compliance statements', body: 'Supplier statements may be based on current knowledge of raw materials and processing, safety data sheets, and limited supplier or third-party assessments. They provide general guidance and do not replace customer-specific qualification or a regulatory assessment.' },
      { heading: 'Article 5: heavy metals and PFAS', body: 'Under Article 5 of Regulation (EU) 2025/40, the combined amount of lead, cadmium, mercury and hexavalent chromium is assessed against a 100 mg/kg limit per packaging component. The supplier statement says these substances are not intentionally added and that representative materials were below the limit; this is not an automatic guarantee for every product or use. PFAS limits for food-contact packaging must be confirmed against intended use and current law.' },
      { heading: 'Other substance topics', body: 'The statements include supplier information that formaldehyde, dimethyl fumarate, oxo-degradable additives, ozone-depleting substances, certain metals, nanomaterials and specified PFAS substances are not intentionally used. PVC, PVdC, specialist films, SVHC and other exceptions can vary by product and must be verified against the product code and technical data sheet.' },
      { heading: 'Rotabil’s approach and limitations', body: 'Rotabil’s carton packaging approach uses current supplier documents, technical data sheets, test reports where necessary, supplier/product/lot traceability and annual document review. This page is not legal advice, a food-contact suitability certificate or an unconditional compliance statement for all products. Final assessment depends on product composition, conditions of use, local infrastructure and applicable law.' },
    ],
    sourceNote: 'Source content: a September 2024 packaging recyclability guide and a 25 June 2026 label-material safety and compliance statement. As stated in the source documents, the information is general and may not reflect every later regulatory change.',
  },
  de: {
    title: 'Deutsche technische Zusammenfassung der Quelldokumente',
    intro: 'Dieser Abschnitt ist eine deutsche Anpassung des Leitfadens zur Recyclingfähigkeit von Verpackungen sowie der Sicherheits- und Konformitätserklärungen für Etikettenmaterialien. Die Quelldokumente werden nicht als separate PDFs veröffentlicht.',
    sections: [
      { heading: 'Recyclingfähigkeit ist eine Systemeigenschaft', body: 'Die Recyclingfähigkeit wird nicht allein durch die Materialbezeichnung bestimmt. Recyclinggerechtes Design, getrennte Sammlung, Sortierung, Aufbereitung und die Nutzung der gewonnenen Sekundärrohstoffe müssen gemeinsam betrachtet werden. Lokale Sammel- und Recyclingstrukturen sowie die tatsächlichen Nutzungsbedingungen beeinflussen das Ergebnis.' },
      { heading: 'EPR und PPWR', body: 'Im Rahmen der erweiterten Herstellerverantwortung (EPR) tragen Hersteller und Importeure Verantwortung für die Entsorgung ihrer Verpackungen am Ende der Nutzungsdauer. In einigen Märkten kann die Recyclingfähigkeit die EPR-Gebühren beeinflussen. Verpackungsart, Gewicht und länderspezifische Meldepflichten sind daher getrennt zu bewerten.' },
      { heading: 'Karton- und Etikettenauswahl', body: 'Standardpapieretiketten auf Kartons können grundsätzlich über bestehende Papier-Recyclingverfahren verarbeitet werden. Faserbasierte Etiketten können die Ausbeute an Recyclingfasern unterstützen. Klebstoffe, die die Fasertrennung erleichtern, sind vorteilhaft; Kunststoffetiketten, nassfeste Papiere und Spezialklebstoffe müssen nach Menge, Design und örtlichen Anlagenregeln gesondert geprüft werden.' },
      { heading: 'Checkliste für nachhaltigere Verpackungen', body: 'Wichtige Prüfungen sind die Reduzierung unnötiger Materialien, ein recyclinggerechtes Design, die Bewertung von Etikett und Klebstoff unter realen Nutzungs- und Recyclingbedingungen, aktuelle Lieferantenerklärungen sowie die Erfassung von Verpackungsart und Gewicht.' },
      { heading: 'Geltungsbereich der Lieferantenerklärungen', body: 'Lieferantenerklärungen können auf Kenntnissen zu Rohstoffen und Verarbeitung, Sicherheitsdatenblättern sowie begrenzten Lieferanten- oder Drittbewertungen beruhen. Sie dienen der allgemeinen Orientierung und ersetzen keine kundenspezifische Qualifizierung oder rechtliche Bewertung.' },
      { heading: 'Artikel 5: Schwermetalle und PFAS', body: 'Nach Artikel 5 der Verordnung (EU) 2025/40 wird die Summe aus Blei, Cadmium, Quecksilber und sechswertigem Chrom je Verpackungskomponente gegen einen Grenzwert von 100 mg/kg bewertet. Die Lieferantenerklärung nennt keine absichtliche Zugabe und Werte unterhalb des Grenzwerts bei repräsentativen Materialien; daraus folgt keine automatische Garantie für jedes Produkt oder jede Anwendung. PFAS-Grenzwerte für Lebensmittelkontaktverpackungen sind anhand des Verwendungszwecks und des geltenden Rechts zu bestätigen.' },
      { heading: 'Weitere Stoffthemen', body: 'Die Erklärungen enthalten Lieferantenangaben zur fehlenden absichtlichen Verwendung von Formaldehyd, Dimethylfumarat, oxo-abbaubaren Zusätzen, ozonschädigenden Stoffen, bestimmten Metallen, Nanomaterialien und genannten PFAS-Stoffen. PVC, PVdC, Spezialfolien, SVHC und weitere Ausnahmen können produktspezifisch sein und müssen anhand von Produktcode und technischem Datenblatt geprüft werden.' },
      { heading: 'Rotabils Ansatz und Grenzen', body: 'Rotabil arbeitet bei Kartonverpackungen mit aktuellen Lieferantendokumenten, technischen Datenblättern, bei Bedarf Prüfberichten, einer Rückverfolgbarkeit von Lieferant, Produkt und Charge sowie einer jährlichen Dokumentenprüfung. Diese Seite ist keine Rechtsberatung, kein Nachweis der Lebensmittelkontakt-Eignung und keine bedingungslose Konformitätserklärung für alle Produkte. Die abschließende Bewertung hängt von Produktzusammensetzung, Nutzung, lokaler Infrastruktur und geltendem Recht ab.' },
    ],
    sourceNote: 'Quelleninhalt: ein Leitfaden zur Recyclingfähigkeit von September 2024 und eine Sicherheits- und Konformitätserklärung für Etikettenmaterialien vom 25. Juni 2026. Nach den Hinweisen der Quelldokumente sind die Informationen allgemein und berücksichtigen möglicherweise nicht jede spätere Rechtsänderung.',
  },
  fr: {
    title: 'Résumé technique en français des documents sources',
    intro: 'Cette section est une adaptation française pour le site de Rotabil du guide sur la recyclabilité des emballages et des déclarations de sécurité et de conformité des matériaux d’étiquettes. Les documents sources ne sont pas publiés sous forme de PDF séparés.',
    sections: [
      { heading: 'La recyclabilité est une propriété du système', body: 'La recyclabilité ne dépend pas uniquement du nom du matériau. La conception pour le recyclage, la collecte séparée, le tri, le retraitement et l’utilisation de la matière secondaire doivent être considérés ensemble. Les infrastructures locales et les conditions réelles d’utilisation influencent le résultat final.' },
      { heading: 'REP et PPWR', body: 'Dans les systèmes de responsabilité élargie du producteur (REP), les producteurs et importateurs assument la gestion des emballages en fin de vie. Dans certains marchés, la recyclabilité peut influencer les contributions REP. Le type, le poids et les obligations déclaratives propres à chaque pays doivent donc être évalués séparément.' },
      { heading: 'Choix du carton et des étiquettes', body: 'Les étiquettes papier standard apposées sur des boîtes en carton peuvent généralement être traitées par les filières papier existantes. Les étiquettes à base de fibres peuvent contribuer au rendement en fibres recyclées. Les adhésifs facilitant la séparation des fibres peuvent être privilégiés ; les étiquettes plastiques, papiers résistants à l’humidité et adhésifs spéciaux nécessitent une analyse selon la quantité, la conception et les règles des installations locales.' },
      { heading: 'Liste de contrôle', body: 'Les contrôles essentiels sont la réduction des matières et composants inutiles, une conception adaptée à la filière de recyclage, l’évaluation de l’ensemble étiquette-adhésif en conditions réelles, la mise à jour des déclarations fournisseurs et l’enregistrement du type et du poids des emballages.' },
      { heading: 'Portée des déclarations fournisseurs', body: 'Les déclarations fournisseurs peuvent se fonder sur les connaissances relatives aux matières premières et aux procédés, les fiches de données de sécurité et des évaluations limitées des fournisseurs ou de tiers. Elles donnent une orientation générale et ne remplacent pas une qualification spécifique du client ou une évaluation réglementaire.' },
      { heading: 'Article 5 : métaux lourds et PFAS', body: 'Selon l’article 5 du règlement (UE) 2025/40, la somme du plomb, du cadmium, du mercure et du chrome hexavalent est évaluée par composant d’emballage avec une limite de 100 mg/kg. La déclaration fournisseur indique l’absence d’ajout intentionnel et des valeurs représentatives inférieures à la limite ; cela ne constitue pas une garantie automatique pour chaque produit ou usage. Les limites PFAS des emballages au contact des aliments doivent être confirmées selon l’usage prévu et le droit en vigueur.' },
      { heading: 'Autres substances', body: 'Les déclarations mentionnent des informations fournisseurs selon lesquelles le formaldéhyde, le fumarate de diméthyle, les additifs oxo-dégradables, les substances appauvrissant la couche d’ozone, certains métaux, les nanomatériaux et certains PFAS ne sont pas ajoutés intentionnellement. Le PVC, le PVdC, les films spéciaux, les SVHC et les exceptions peuvent varier selon le produit et doivent être vérifiés avec la référence et la fiche technique.' },
      { heading: 'Approche et limites de Rotabil', body: 'Pour les emballages carton, Rotabil utilise des documents fournisseurs à jour, des fiches techniques, des rapports d’essai si nécessaire, une traçabilité fournisseur-produit-lot et une revue documentaire annuelle. Cette page n’est ni un conseil juridique, ni un certificat d’aptitude au contact alimentaire, ni une déclaration de conformité inconditionnelle pour tous les produits. L’évaluation finale dépend de la composition, de l’usage, des infrastructures locales et du droit applicable.' },
    ],
    sourceNote: 'Contenu source : un guide de recyclabilité publié en septembre 2024 et une déclaration de sécurité et de conformité des matériaux d’étiquettes datée du 25 juin 2026. Selon les avertissements des sources, ces informations sont générales et peuvent ne pas intégrer toutes les évolutions réglementaires ultérieures.',
  },
  es: {
    title: 'Resumen técnico en español de los documentos fuente',
    intro: 'Esta sección es una adaptación al español para el sitio de Rotabil de la guía de reciclabilidad de envases y de las declaraciones de seguridad y cumplimiento de materiales para etiquetas. Los documentos fuente no se publican como PDF independientes.',
    sections: [
      { heading: 'La reciclabilidad es una propiedad del sistema', body: 'La reciclabilidad no depende únicamente del nombre del material. Deben considerarse conjuntamente el diseño para el reciclaje, la recogida separada, la clasificación, el reprocesamiento y el uso de la materia prima secundaria resultante. La infraestructura local y las condiciones reales de uso influyen en el resultado.' },
      { heading: 'RAP y PPWR', body: 'En los sistemas de Responsabilidad Ampliada del Productor (RAP), productores e importadores asumen la gestión de los envases al final de su vida útil. En algunos mercados, la reciclabilidad puede influir en las tarifas RAP. Por ello, el tipo, el peso y las obligaciones de información de cada país deben evaluarse por separado.' },
      { heading: 'Elección de cartón y etiquetas', body: 'Las etiquetas de papel estándar sobre cajas de cartón pueden gestionarse generalmente mediante los métodos existentes de reciclaje de papel. Las etiquetas de fibra pueden contribuir al rendimiento de fibra recuperada. Los adhesivos que facilitan la separación de fibras pueden ser preferibles; las etiquetas plásticas, papeles resistentes a la humedad y adhesivos especiales requieren una revisión específica.' },
      { heading: 'Lista de comprobación', body: 'Los controles principales son reducir materiales y componentes innecesarios, diseñar para el flujo de reciclaje correspondiente, evaluar la combinación etiqueta-adhesivo en condiciones reales, mantener actualizadas las declaraciones de proveedores y registrar el tipo y peso del envase.' },
      { heading: 'Alcance de las declaraciones de proveedores', body: 'Las declaraciones pueden basarse en el conocimiento de materias primas y procesos, fichas de datos de seguridad y evaluaciones limitadas de proveedores o terceros. Proporcionan orientación general y no sustituyen la cualificación específica del cliente ni una evaluación normativa.' },
      { heading: 'Artículo 5: metales pesados y PFAS', body: 'Según el artículo 5 del Reglamento (UE) 2025/40, la suma de plomo, cadmio, mercurio y cromo hexavalente se evalúa por componente del envase con un límite de 100 mg/kg. La declaración del proveedor indica que no se añaden intencionadamente y que los materiales representativos están por debajo del límite; esto no es una garantía automática para todos los productos o usos. Los límites de PFAS para contacto alimentario deben confirmarse según el uso previsto y la legislación vigente.' },
      { heading: 'Otros grupos de sustancias', body: 'Las declaraciones incluyen información del proveedor sobre la no adición intencionada de formaldehído, fumarato de dimetilo, aditivos oxodegradables, sustancias que agotan el ozono, determinados metales, nanomateriales y PFAS especificados. PVC, PVdC, películas especiales, SVHC y otras excepciones pueden variar por producto y deben verificarse con la referencia y la ficha técnica.' },
      { heading: 'Enfoque y límites de Rotabil', body: 'Para los envases de cartón, Rotabil utiliza documentos de proveedores actualizados, fichas técnicas, informes de ensayo cuando son necesarios, trazabilidad proveedor-producto-lote y revisión documental anual. Esta página no es asesoramiento jurídico, certificado de aptitud para contacto alimentario ni declaración incondicional de cumplimiento para todos los productos. La evaluación final depende de la composición, el uso, la infraestructura local y la legislación aplicable.' },
    ],
    sourceNote: 'Contenido fuente: una guía de reciclabilidad de septiembre de 2024 y una declaración de seguridad y cumplimiento de materiales para etiquetas de 25 de junio de 2026. Según las advertencias de los documentos, la información es general y puede no reflejar todos los cambios normativos posteriores.',
  },
  it: {
    title: 'Sintesi tecnica in italiano dei documenti di riferimento',
    intro: 'Questa sezione è un adattamento in italiano per il sito Rotabil della guida alla riciclabilità degli imballaggi e delle dichiarazioni di sicurezza e conformità dei materiali per etichette. I documenti originali non sono pubblicati come PDF separati.',
    sections: [
      { heading: 'La riciclabilità è una proprietà del sistema', body: 'La riciclabilità non dipende soltanto dal nome del materiale. Devono essere considerati insieme progettazione per il riciclo, raccolta separata, selezione, ritrattamento e uso della materia prima secondaria ottenuta. Le infrastrutture locali e le condizioni reali d’uso influenzano il risultato.' },
      { heading: 'EPR e PPWR', body: 'Nei sistemi di responsabilità estesa del produttore (EPR), produttori e importatori sono responsabili della gestione degli imballaggi a fine vita. In alcuni mercati la riciclabilità può influire sui contributi EPR. Tipo, peso e obblighi di comunicazione nazionali devono quindi essere valutati separatamente.' },
      { heading: 'Scelta di cartone ed etichette', body: 'Le etichette standard in carta sulle scatole di cartone possono generalmente essere gestite con i metodi esistenti di riciclo della carta. Le etichette a base di fibre possono sostenere la resa di fibre recuperate. Adesivi che facilitano la separazione delle fibre possono essere preferiti; etichette plastiche, carte resistenti all’umidità e adesivi speciali richiedono una verifica specifica.' },
      { heading: 'Lista di controllo', body: 'I controlli principali comprendono la riduzione di materiali e componenti non necessari, la progettazione per il relativo flusso di riciclo, la valutazione della combinazione etichetta-adesivo in condizioni reali, l’aggiornamento delle dichiarazioni dei fornitori e la registrazione di tipo e peso dell’imballaggio.' },
      { heading: 'Ambito delle dichiarazioni dei fornitori', body: 'Le dichiarazioni possono basarsi sulle conoscenze di materie prime e processi, sulle schede di sicurezza e su valutazioni limitate di fornitori o terzi. Forniscono indicazioni generali e non sostituiscono la qualificazione specifica del cliente o una valutazione normativa.' },
      { heading: 'Articolo 5: metalli pesanti e PFAS', body: 'Ai sensi dell’articolo 5 del regolamento (UE) 2025/40, la somma di piombo, cadmio, mercurio e cromo esavalente viene valutata per componente dell’imballaggio con un limite di 100 mg/kg. La dichiarazione del fornitore indica che tali sostanze non vengono aggiunte intenzionalmente e che i materiali rappresentativi sono sotto il limite; ciò non costituisce una garanzia automatica per ogni prodotto o uso. I limiti PFAS per il contatto alimentare devono essere confermati in base all’uso previsto e alla normativa vigente.' },
      { heading: 'Altre sostanze', body: 'Le dichiarazioni riportano informazioni del fornitore sulla mancata aggiunta intenzionale di formaldeide, fumarato di dimetile, additivi oxo-degradabili, sostanze che riducono l’ozono, determinati metalli, nanomateriali e PFAS specificati. PVC, PVdC, film speciali, SVHC e altre eccezioni possono variare per prodotto e devono essere verificati con codice e scheda tecnica.' },
      { heading: 'Approccio e limiti di Rotabil', body: 'Per gli imballaggi in cartone Rotabil utilizza documenti aggiornati dei fornitori, schede tecniche, rapporti di prova quando necessari, tracciabilità fornitore-prodotto-lotto e revisione documentale annuale. Questa pagina non è consulenza legale, certificato di idoneità al contatto alimentare né dichiarazione incondizionata di conformità per tutti i prodotti. La valutazione finale dipende da composizione, uso, infrastrutture locali e legge applicabile.' },
    ],
    sourceNote: 'Contenuto di riferimento: una guida alla riciclabilità di settembre 2024 e una dichiarazione di sicurezza e conformità dei materiali per etichette del 25 giugno 2026. Come indicato nelle fonti, le informazioni sono generali e potrebbero non riflettere tutte le successive modifiche normative.',
  },
  ar: {
    title: 'ملخص فني باللغة العربية للوثائق المصدر',
    intro: 'هذا القسم هو تكييف عربي لموقع روتابيل لمحتوى دليل قابلية إعادة تدوير العبوات وبيانات السلامة والامتثال الخاصة بمواد الملصقات. لن يتم نشر الوثائق المصدر كملفات PDF مستقلة.',
    sections: [
      { heading: 'قابلية إعادة التدوير خاصية للنظام', body: 'لا تعتمد قابلية إعادة التدوير على اسم المادة وحده. يجب النظر معاً إلى التصميم من أجل إعادة التدوير والجمع المنفصل والفرز وإعادة المعالجة واستخدام المواد الخام الثانوية الناتجة. كما تؤثر البنية التحتية المحلية وشروط الاستخدام الفعلية في النتيجة النهائية.' },
      { heading: 'مسؤولية المنتج الممتدة واللائحة PPWR', body: 'في أنظمة مسؤولية المنتج الممتدة، يتحمل المنتجون والمستوردون مسؤولية إدارة العبوات عند نهاية عمرها. وقد تؤثر قابلية إعادة التدوير في الرسوم ببعض الأسواق. لذلك يجب تقييم نوع العبوة ووزنها وقواعد الإبلاغ الخاصة بكل دولة بشكل منفصل.' },
      { heading: 'اختيار الكرتون والملصقات', body: 'يمكن عادةً معالجة الملصقات الورقية القياسية على الصناديق الكرتونية من خلال طرق إعادة تدوير الورق الحالية. وقد تدعم الملصقات الليفية إنتاج الألياف المسترجعة. يمكن تفضيل المواد اللاصقة التي تسهّل فصل الألياف، بينما تحتاج الملصقات البلاستيكية والورق المقاوم للرطوبة والمواد اللاصقة الخاصة إلى مراجعة منفصلة وفق الكمية والتصميم وقواعد المنشآت المحلية.' },
      { heading: 'قائمة التحقق', body: 'تشمل نقاط التحقق تقليل المواد والمكونات غير الضرورية، والتصميم لمسار إعادة التدوير المناسب، وتقييم تركيبة الملصق واللاصق في ظروف الاستخدام وإعادة التدوير الفعلية، وتحديث إقرارات الموردين، وتسجيل نوع العبوة ووزنها.' },
      { heading: 'نطاق بيانات السلامة والامتثال من الموردين', body: 'قد تستند بيانات الموردين إلى المعرفة بالمواد الخام وعمليات التصنيع ونشرات بيانات السلامة وتقييمات محدودة من الموردين أو أطراف ثالثة. وهي تقدم إرشاداً عاماً ولا تحل محل تأهيل خاص بالعميل أو تقييم تنظيمي.' },
      { heading: 'المادة 5: المعادن الثقيلة وPFAS', body: 'بموجب المادة 5 من اللائحة الأوروبية 2025/40، يتم تقييم مجموع الرصاص والكادميوم والزئبق والكروم سداسي التكافؤ بحد 100 ملغم/كغم لكل مكوّن من مكونات العبوة. ويشير بيان المورد إلى عدم الإضافة المتعمدة وإلى أن المواد الممثلة كانت تحت الحد؛ ولا يمثل ذلك ضماناً تلقائياً لكل منتج أو استخدام. يجب تأكيد حدود PFAS للعبوات الملامسة للغذاء وفق الاستخدام المقصود والقانون الساري.' },
      { heading: 'موضوعات مواد أخرى', body: 'تتضمن البيانات معلومات من المورد تفيد بعدم الاستخدام المتعمد للفورمالديهايد وفومارات ثنائي الميثيل والإضافات القابلة للتحلل بالأكسدة والمواد المستنزفة للأوزون وبعض المعادن والمواد النانوية ومواد PFAS المحددة. وقد تختلف حالات PVC وPVdC والأفلام الخاصة وSVHC والاستثناءات حسب المنتج، ويجب التحقق منها من خلال رمز المنتج والوثيقة الفنية.' },
      { heading: 'نهج روتابيل وحدوده', body: 'يعتمد نهج روتابيل لعبوات الكرتون على وثائق الموردين الحالية والوثائق الفنية وتقارير الاختبار عند الحاجة وتتبع المورد والمنتج والدفعة والمراجعة السنوية للوثائق. هذه الصفحة ليست استشارة قانونية ولا شهادة صلاحية لملامسة الغذاء ولا إقرار امتثال غير مشروط لجميع المنتجات. يعتمد التقييم النهائي على تركيبة المنتج وشروط الاستخدام والبنية التحتية المحلية والقانون الساري.' },
    ],
    sourceNote: 'محتوى المصادر: دليل لقابلية إعادة تدوير العبوات منشور في سبتمبر 2024 وبيان سلامة وامتثال لمواد الملصقات مؤرخ في 25 يونيو 2026. ووفق تنبيهات الوثائق، فإن المعلومات عامة وقد لا تعكس جميع التغييرات التنظيمية اللاحقة.',
  },
};

export function PPWRDocumentContent({ locale }: { locale: string }) {
  const document = documents[locale] ?? documents.en;

  return (
    <section className="mt-12 border-t border-slate-200 pt-10" aria-labelledby="translated-source-documents">
      <h2 id="translated-source-documents" className="text-2xl font-bold text-slate-900">{document.title}</h2>
      <p className="mt-4 text-slate-600">{document.intro}</p>
      <div className="mt-8 space-y-8">
        {document.sections.map((section) => (
          <div key={section.heading}>
            <h3 className="text-xl font-bold text-slate-900">{section.heading}</h3>
            <p className="mt-3 text-slate-600 leading-7">{section.body}</p>
          </div>
        ))}
      </div>
      <p className="mt-10 rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm leading-6 text-slate-500">{document.sourceNote}</p>
    </section>
  );
}
